[project]
name = "vllm"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jakub 'lambdaofgod' Bartczuk <bartczukkuba@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
server = "VLLM_USE_MODELSCOPE=True python -m vllm.entrypoints.api_server  --trust-remote-code"
starcoder = "python -m vllm.entrypoints.api_server  --trust-remote-code --model='bigcode/starcoderbase-3b'"

[dependencies]
python = "3.10.*"
pip = "23.3.1.*"
